'use client';
import { Icon, BrandMark } from './brand';
import { labels } from '@/lib/pilot/domain';
// API response is validated at the service boundary.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Obj=Record<string,any>;
export function JourneyHome({data,profile,urgent,onNavigate,onRefresh,onStart,busy}:{data:Obj;profile:Obj;urgent:boolean;onNavigate:(tab:string)=>void;onRefresh:()=>void;onStart:()=>void;busy:boolean}){
  const record=data.record,plan=data.plans[0],hasStarted=!!record.consent_at||!!profile.firstName;
  const paid=data.orders.some((o:Obj)=>o.status==='paid');
  const needsInfo=record.status==='needs_information',waiting=record.status==='submitted';
  const nextAction=plan?.actions.find((a:Obj)=>a.owner==='member'&&!data.updates.filter((u:Obj)=>u.plan_id===plan.id&&u.action_id===a.id).at(-1)?.done);
  const activeTasks=data.tasks.filter((t:Obj)=>!['completed','cancelled'].includes(t.status));
  if(!hasStarted&&!plan)return <section className="j-welcome j-scene"><div className="j-welcome-art" aria-hidden="true"><span className="j-orbit j-orbit-one"/><span className="j-orbit j-orbit-two"/><span className="j-orbit-dot"/><div className="j-welcome-mark"><BrandMark/></div></div><span className="p-eyebrow">خوش آمدید؛ اینجا از شما شروع می‌کنیم</span><h1>از حالِ امروز،<br/><em>به قدم بعدیِ روشن.</em></h1><p>بگویید برای چه چیزی کمک می‌خواهید. چند سؤال کوتاه می‌پرسیم تا پزشک با شناخت بهتری همراه‌تان شود.</p><button className="p-primary j-start" onClick={onStart}>شروع آشنایی <Icon name="arrow" size={20}/></button><small>هر جا خواستید مکث کنید؛ بعد از پذیرش رضایت، پاسخ‌ها ذخیره می‌شوند.</small><div className="j-welcome-path"><span>شناخت شما</span><i/><span>بررسی پزشک</span><i/><span>قدم بعدی شما</span></div></section>;
  if(urgent)return <section className="j-state p-card j-scene"><span className="j-state-icon"><Icon name="doctor" size={30}/></span><h1>قدم بعدی، بررسی پزشک است</h1><p>پاسخ‌های شما نیاز به بررسی علامت هشدار دارند. برای این بررسی نیازی به پرداخت نیست. راهنمای مراجعهٔ فوری در همین صفحه را بخوانید.</p><button className="p-secondary" onClick={()=>onNavigate('intake')}>مشاهده و تکمیل پاسخ‌ها</button></section>;
  return <div className="j-home j-scene"><section className={`j-state p-card ${plan&&!needsInfo&&!waiting?'j-published':''}`}><span className="p-eyebrow">{profile.firstName?`${profile.firstName} عزیز، `:''}این نقطهٔ مسیر شماست</span><span className="j-state-icon"><Icon name={needsInfo?'file':waiting?'clock':plan?'check':'route'} size={30}/></span><h1>{needsInfo?'پزشک به توضیح شما نیاز دارد':waiting?'پاسخ‌ها رسید؛ حالا نوبت پزشک است':plan?'برنامهٔ شما آماده است':paid?'پرداخت ثبت شد؛ پرونده را ارسال کنید':'از همان‌جا که بودید ادامه دهید'}</h1><p>{needsInfo?record.information_request:waiting?`${data.clinician?.name||'پزشک مسئول'} پاسخ‌ها و مدارک را بررسی می‌کند. فعلاً کاری از طرف شما لازم نیست. نتیجهٔ بررسی یا درخواست توضیح بیشتر همین‌جا نمایش داده می‌شود.`:plan?plan.summary:paid?'پرداخت به‌تنهایی پرونده را ارسال نمی‌کند. پاسخ‌ها را مرور کنید و «ارسال برای بررسی پزشک» را بزنید.':'پاسخ‌های ذخیره‌شده محفوظ‌اند؛ نیازی به وارد کردن دوبارهٔ آن‌ها نیست.'}</p>{waiting?<button className="p-secondary" disabled={busy} onClick={onRefresh}>بررسی نتیجهٔ پزشک</button>:<button className="p-primary" onClick={()=>onNavigate(plan&&!needsInfo?'plan':'intake')}>{needsInfo?'تکمیل توضیح و ارسال دوباره':plan?'دیدن برنامه و قدم‌های من':paid?'مرور و ارسال پرونده':'ادامهٔ گفت‌وگو'}</button>}{needsInfo&&paid&&<small>برای تکمیل همین بررسی، پرداخت دوباره لازم نیست.</small>}{waiting&&<small>زمان قطعی پاسخ هنوز اعلام نشده است؛ برای پیگیری می‌توانید به پشتیبانی پیام دهید.</small>}</section>
    {plan&&<section className="j-next-step p-card"><span className="p-eyebrow">قدم بعدی</span><h2>{nextAction?.title||(activeTasks.length?'تیم هماهنگی در حال پیگیری است':'گزارش اقدامات شما ثبت شده است')}</h2><p>{nextAction?.reason||(activeTasks.length?'پس از اقدام کارشناس، مرکز، زمان و نتیجه در بخش هماهنگی نمایش داده می‌شود.':'ثبت انجام کارها به‌معنای تأیید بهبود پزشکی نیست؛ پیگیری بعدی مطابق برنامهٔ پزشک است.')}</p><button className="p-link" onClick={()=>onNavigate(nextAction?'plan':activeTasks.length?'appointments':'plan')}>{nextAction?'مشاهده و ثبت انجام':activeTasks.length?'مشاهده هماهنگی':'مرور برنامه'}</button></section>}
    {data.tasks.length>0&&<section className="p-card j-coordination"><h2>آخرین وضعیت هماهنگی</h2>{data.tasks.slice(0,2).map((task:Obj)=><div key={task.id}><strong>{task.title}</strong><span className={`p-tag ${task.status}`}>{labels[task.status]||task.status}</span><p>{task.note||(task.status==='requested'?'درخواست ثبت شده؛ کارشناس هنوز نتیجه‌ای ثبت نکرده است.':task.status==='contacted'?'هماهنگی در جریان است؛ هنوز نوبت قطعی نشده.':task.status==='confirmed'?`${task.provider} · ${task.scheduled_at}`:'جزئیات را در هماهنگی ببینید.')}</p></div>)}<button className="p-link" onClick={()=>onNavigate('appointments')}>جزئیات هماهنگی</button></section>}
    <div className="j-quiet-links"><button className="p-link" onClick={()=>onNavigate('health')}>مشاهده اطلاعات ثبت‌شده</button>{plan&&(needsInfo||waiting)&&<button className="p-link" onClick={()=>onNavigate('plan')}>برنامهٔ منتشرشدهٔ قبلی</button>}<button className="p-link" onClick={()=>onNavigate('support')}>نیاز به کمک دارم</button></div>
  </div>;
}
