'use client';
import { useState } from 'react';
import { LivingScene, SceneMotionControl } from './living-scene';
import { Arrival } from './arrival';
import { Icon } from './brand';
import { labels } from '@/lib/pilot/domain';
import { redFlagQuestionIds } from '@/lib/assessment-definition';
// API response is validated at the service boundary.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Obj=Record<string,any>;
export function JourneyHome({data,profile,urgent,urgentCurrent,onUrgent,onNavigate,onRefresh,onStart,busy,readOnly=false}:{data:Obj;profile:Obj;urgent:boolean;urgentCurrent?:boolean;onUrgent?:()=>void;onNavigate:(tab:string)=>void;onRefresh:()=>void;onStart:()=>void;busy:boolean;readOnly?:boolean}){
  const [paused,setPaused]=useState(false);
  const record=data.record,plan=data.plans[0],hasStarted=!!record.consent_at||!!profile.firstName;
  const activeUrgent=urgentCurrent??[...redFlagQuestionIds].some(id=>record.answers?.[id]==='yes');
  const paid=data.orders.some((o:Obj)=>o.status==='paid');
  const needsInfo=record.status==='needs_information',waiting=record.status==='submitted';
  const nextAction=plan?.actions.find((a:Obj)=>a.owner==='member'&&!data.updates.filter((u:Obj)=>u.plan_id===plan.id&&u.action_id===a.id).at(-1)?.done);
  const activeTasks=data.tasks.filter((t:Obj)=>!['completed','cancelled'].includes(t.status));
  if(!hasStarted&&!plan)return <Arrival onStart={onStart}/>;
  if(urgent)return <section className="j-state p-card j-scene"><span className="j-state-icon"><Icon name={activeUrgent?'phone':'doctor'} size={30}/></span><h1>{activeUrgent?'اول، برای حالتان کمک بگیرید':'علامت ثبت‌شده هنوز بررسی نشده'}</h1><p>{activeUrgent?'برای علامتی که ثبت کرده‌اید، همین حالا با اورژانس ۱۱۵ تماس بگیرید و طبق راهنمایی اپراتور عمل کنید. منتظر ادامهٔ فرم یا پاسخ در سامانه نمانید.':'پاسخ‌های فعلی شما حفظ شده‌اند. تغییر پاسخ، علامتی را که قبلاً اعلام کرده‌اید خودکار نمی‌بندد؛ این مورد به بررسی پزشک نیاز دارد. اگر اکنون علامت دارید، از راهنمای کمک فوری استفاده کنید و منتظر پاسخ در سامانه نمانید.'}</p><div className="p-actions"><button className="p-primary" onClick={onUrgent||(()=>onNavigate('intake'))}>{activeUrgent?'راهنمای تماس و کمک فوری':'راهنمای کمک فوری'}</button><button className="p-link" onClick={()=>onNavigate('intake')}>مرور پاسخ‌های من</button></div></section>;
  const stage=waiting||needsInfo?1:plan?2:0;
  return <div className="j-home"><section className={`care-home ${plan&&!needsInfo&&!waiting?'care-published':''}`}><div className="care-copy"><span className="p-eyebrow">{profile.firstName?`${profile.firstName} عزیز، `:''}این نقطهٔ مسیر شماست</span><span className="care-state"><Icon name={needsInfo?'file':waiting?'clock':plan?'check':'route'} size={17}/>{needsInfo?'توضیح تکمیلی':waiting?'در حال بررسی':plan?'برنامه منتشر شد':'در مسیر آشنایی'}</span><h1>{needsInfo?'پزشک به توضیح شما نیاز دارد':waiting?'پاسخ‌ها رسید؛ حالا نوبت پزشک است':plan?'برنامهٔ شما آماده است':paid?'پرداخت ثبت شد؛ پرونده را ارسال کنید':'از همان‌جا که بودید ادامه دهید'}</h1><p>{needsInfo?record.information_request:waiting?`${data.clinician?.name||'پزشک مسئول'} پاسخ‌ها و مدارک را بررسی می‌کند. فعلاً کاری از طرف شما لازم نیست. نتیجهٔ بررسی یا درخواست توضیح بیشتر همین‌جا نمایش داده می‌شود.`:plan?'پزشک پروندهٔ شما را بررسی کرده و قدم‌های بعدی را مشخص کرده است. از یک قدم شروع کنید؛ برنامه و همراهی تیم در دسترس شماست.':paid?'پرداخت به‌تنهایی پرونده را ارسال نمی‌کند. پاسخ‌ها را مرور کنید و «ارسال برای بررسی پزشک» را بزنید.':'پاسخ‌های ذخیره‌شده محفوظ‌اند؛ نیازی به وارد کردن دوبارهٔ آن‌ها نیست.'}</p>{waiting?<button className="p-secondary" disabled={busy} onClick={onRefresh}>بررسی نتیجهٔ پزشک</button>:<button className="p-primary" onClick={()=>onNavigate(plan&&!needsInfo?'plan':'intake')}>{needsInfo?'تکمیل توضیح و ارسال دوباره':plan?'دیدن برنامه و قدم‌های من':paid?'مرور و ارسال پرونده':'ادامهٔ گفت‌وگو'}</button>}{needsInfo&&paid&&<small>برای تکمیل همین بررسی، پرداخت دوباره لازم نیست.</small>}{waiting&&<small>زمان قطعی پاسخ هنوز اعلام نشده است؛ برای پیگیری می‌توانید به پشتیبانی پیام دهید.</small>}<ol className="care-path" aria-label="وضعیت مسیر پرونده">{['آشنایی با شما','بررسی پزشک','برنامهٔ من'].map((label,i)=><li key={label} className={i<stage?'done':i===stage?'current':''} aria-current={i===stage?'step':undefined}><span>{i<stage?<Icon name="check" size={13}/>:['۱','۲','۳'][i]}</span>{label}</li>)}</ol></div><div className="care-art"><LivingScene small surface="light" paused={paused}/><div className="care-art-label"><span>سلامت، قدم به قدم</span><strong>{waiting?'همراه شما در مسیر بررسی':plan?'مسیر شما، با همراهی پزشک':'هر قدم، از شناخت شما'}</strong></div><SceneMotionControl className="care-motion" paused={paused} onChange={setPaused}/></div></section>
    {plan&&<section className="j-next-step p-card"><span className="care-next-icon" aria-hidden="true"><Icon name="arrow" size={21}/></span><span className="p-eyebrow">قدم بعدی</span><h2>{nextAction?.title||(activeTasks.length?'تیم هماهنگی در حال پیگیری است':'گزارش اقدامات شما ثبت شده است')}</h2><p>{nextAction?.reason||(activeTasks.length?'پس از اقدام کارشناس، مرکز، زمان و نتیجه در بخش هماهنگی نمایش داده می‌شود.':'ثبت انجام کارها به‌معنای تأیید بهبود پزشکی نیست؛ پیگیری بعدی مطابق برنامهٔ پزشک است.')}</p><button className="p-link" onClick={()=>onNavigate(nextAction?'plan':activeTasks.length?'appointments':'plan')}>{nextAction?'مشاهده و ثبت انجام':activeTasks.length?'مشاهده هماهنگی':'مرور برنامه'}</button></section>}
    {data.tasks.length>0&&<section className="p-card j-coordination"><h2>آخرین وضعیت هماهنگی</h2>{data.tasks.slice(0,2).map((task:Obj)=><div key={task.id}><strong>{task.title}</strong><span className={`p-tag ${task.status}`}>{labels[task.status]||task.status}</span><p>{task.note||(task.status==='requested'?'درخواست ثبت شده؛ کارشناس هنوز نتیجه‌ای ثبت نکرده است.':task.status==='contacted'?'هماهنگی در جریان است؛ هنوز نوبت قطعی نشده.':task.status==='confirmed'?`${task.provider} · ${task.scheduled_at}`:'جزئیات را در هماهنگی ببینید.')}</p></div>)}<button className="p-link" onClick={()=>onNavigate('appointments')}>جزئیات هماهنگی</button></section>}
    <div className="j-quiet-links"><button className="p-link" onClick={()=>onNavigate('health')}>مشاهده اطلاعات ثبت‌شده</button>{plan&&(needsInfo||waiting)&&<button className="p-link" onClick={()=>onNavigate('plan')}>برنامهٔ منتشرشدهٔ قبلی</button>}{!readOnly&&<button className="p-link" onClick={()=>onNavigate('support')}>نیاز به کمک دارم</button>}</div>
  </div>;
}
