'use client';
import { useEffect, useRef, useState } from 'react';
import type { Map as LeafletMap } from 'leaflet';
import type { BookingLocation } from '../../lib/pilot/location';
import 'leaflet/dist/leaflet.css';
const empty:BookingLocation={address:'',unit:'',entrance:'',latitude:null,longitude:null,confirmed:false};
type Place={lat:string;lon:string;display_name:string};
export function LocationPicker({value,onChange}:{value?:BookingLocation;onChange:(v:BookingLocation)=>void}) {
 const v=value||empty,[open,O]=useState(false),[candidate,C]=useState(v),[query,Q]=useState(''),[results,R]=useState<Place[]>([]),[notice,N]=useState(''),[loading,L]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),canvas=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),opener=useRef<HTMLButtonElement>(null),request=useRef<AbortController|null>(null),lastRequest=useRef(0),cache=useRef(new globalThis.Map<string,unknown>());
 useEffect(()=>{if(!open)return;let active=true;dialog.current?.showModal();void import('leaflet').then(module=>{if(!active||!canvas.current)return;const leaflet=module.default;const m=leaflet.map(canvas.current).setView([v.latitude??32.5,v.longitude??53.5],v.latitude===null?5:15);map.current=m;leaflet.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> contributors'}).on('tileerror',()=>N('نقشه بارگذاری نشد؛ می‌توانید آدرس را دستی وارد کنید.')).addTo(m);m.on('moveend',()=>{const point=m.getCenter();C(old=>({...old,latitude:Number(point.lat.toFixed(6)),longitude:Number(point.lng.toFixed(6)),confirmed:false}));});});return()=>{active=false;request.current?.abort();map.current?.remove();map.current=null;};
 // The candidate is private until explicit confirmation.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[open]);
 function close(){O(false);request.current?.abort();dialog.current?.close();opener.current?.focus();}
 async function lookup(reverse=false) {
  if(loading)return;
  if(!reverse&&query.trim().length<3){N('نام شهر، خیابان یا مکان را با حداقل سه حرف وارد کنید.');return;}
  if(reverse&&(candidate.latitude===null||candidate.longitude===null)){N('ابتدا نقطه را روی نقشه انتخاب کنید.');return;}
  if(Date.now()-lastRequest.current<1100){N('یک لحظه صبر کنید و سپس دوباره جست‌وجو کنید.');return;}
  const params=new URLSearchParams(reverse?{lat:String(candidate.latitude),lon:String(candidate.longitude),format:'jsonv2','accept-language':'fa'}:{q:query.trim(),countrycodes:'ir',format:'jsonv2',limit:'5','accept-language':'fa'});
  const url='https://nominatim.openstreetmap.org/'+(reverse?'reverse':'search')+'?'+params;
  L(true);N('');lastRequest.current=Date.now();const controller=new AbortController();request.current=controller;const timeout=setTimeout(()=>controller.abort(),8000);
  try{let data=cache.current.get(url);if(!data){const response=await fetch(url,{signal:controller.signal,credentials:'omit',referrerPolicy:'strict-origin-when-cross-origin'});if(!response.ok)throw new Error();data=await response.json();cache.current.set(url,data);}if(controller.signal.aborted)return;if(reverse){const place=data as Place;if(!place.display_name)throw new Error();C(old=>({...old,address:place.display_name.slice(0,500)}));N('آدرس پیشنهادی را بررسی و اصلاح کنید.');}else{const places=data as Place[];R(places);if(!places.length)N('نتیجه‌ای پیدا نشد؛ آدرس دستی همیشه در دسترس است.');}}
  catch{if(!controller.signal.aborted||dialog.current?.open)N('جست‌وجوی نقشه در دسترس نیست؛ آدرس را دستی وارد کنید.');}finally{clearTimeout(timeout);L(false);}
 }
 function locate(){if(!navigator.geolocation){N('موقعیت‌یابی پشتیبانی نمی‌شود؛ نقطه یا آدرس را دستی تعیین کنید.');return;}N('در انتظار اجازه و موقعیت دستگاه…');navigator.geolocation.getCurrentPosition(p=>{if(!dialog.current?.open)return;map.current?.setView([p.coords.latitude,p.coords.longitude],16);C(old=>({...old,latitude:p.coords.latitude,longitude:p.coords.longitude}));N(`دقت اعلام‌شده حدود ${Math.round(p.coords.accuracy).toLocaleString('fa-IR')} متر است؛ نقطه و آدرس را بررسی کنید.`);},()=>N('اجازه یا موقعیت دقیق در دسترس نیست؛ ورود دستی آدرس امکان‌پذیر است.'),{timeout:10000,maximumAge:0,enableHighAccuracy:true});}
 return <section className="ux-location"><h3>آدرس خدمت در محل (نمایشی)</h3><p>آدرس و موقعیت فقط برای همین درخواست ذخیره می‌شوند. مختصات پس از پایان یا لغو درخواست حذف می‌شوند.</p><button ref={opener} type="button" className="p-secondary" onClick={()=>{C(v);N('');R([]);O(true);}}>انتخاب روی نقشه</button><p className="p-muted">نقشه اختیاری است. با بازکردن آن، کاشی‌های OpenStreetMap دریافت می‌شوند؛ فقط عبارت جست‌وجو یا مختصاتِ درخواست‌شده به Nominatim می‌رود. اطلاعات پرونده ارسال نمی‌شود.</p>
 {(['address','unit','entrance'] as const).map((key,i)=><label className="p-field" key={key}><span>{['آدرس دقیق','پلاک و واحد (اختیاری)','توضیح ورود (اختیاری)'][i]}</span><input maxLength={key==='address'?500:key==='unit'?80:200} value={v[key]} onChange={e=>onChange({...v,[key]:e.target.value,confirmed:false})}/></label>)}
 {v.latitude!==null&&<p>نقطه انتخابی: <bdi>{v.latitude.toFixed(5)}, {v.longitude?.toFixed(5)}</bdi><button type="button" className="p-link" onClick={()=>onChange({...v,latitude:null,longitude:null,confirmed:false})}>حذف نقطه و استفاده از آدرس دستی</button></p>}<label className="p-choice"><input type="checkbox" checked={v.confirmed} onChange={e=>onChange({...v,confirmed:e.target.checked})}/>آدرس و نقطه احتمالی را بررسی و تأیید می‌کنم.</label>
 {open&&<dialog ref={dialog} className="ux-map-dialog" dir="rtl" aria-label="انتخاب موقعیت خدمت" onCancel={e=>{e.preventDefault();close();}}><header><h2>انتخاب موقعیت</h2><button type="button" onClick={close} aria-label="بستن نقشه بدون ذخیره">×</button></header><label>جست‌وجوی مکان (بدون اطلاعات پزشکی)<input value={query} onChange={e=>Q(e.target.value)} maxLength={200}/></label><div className="ux-map-controls"><button type="button" disabled={loading} onClick={()=>void lookup()}>جست‌وجوی مکان</button><button type="button" onClick={locate}>موقعیت فعلی من</button></div><div className="ux-map-results">{results.map(p=><button key={p.lat+':'+p.lon} onClick={()=>{map.current?.setView([Number(p.lat),Number(p.lon)],16);C(old=>({...old,address:p.display_name.slice(0,500),latitude:Number(p.lat),longitude:Number(p.lon)}));R([]);}}>{p.display_name}</button>)}</div><div className="ux-map-frame"><div className="ux-map" ref={canvas}/><span className="ux-map-pin" aria-hidden="true">⌖</span></div><p>نقشه را زیر نشانگر ثابت جابه‌جا کنید. برای حرکت با صفحه‌کلید، نقشه را انتخاب کنید و از کلیدهای جهت استفاده کنید.</p><button type="button" disabled={loading||candidate.latitude===null} onClick={()=>void lookup(true)}>دریافت آدرس نقطه</button><label>پیش‌نمایش آدرس؛ قابل اصلاح<textarea value={candidate.address} maxLength={500} onChange={e=>C(old=>({...old,address:e.target.value}))}/></label>{candidate.latitude!==null&&<p><bdi>{candidate.latitude.toFixed(5)}, {candidate.longitude?.toFixed(5)}</bdi></p>}<p role="status">{loading?'در حال جست‌وجو…':notice}</p><div className="p-actions"><button className="p-primary" type="button" disabled={candidate.address.trim().length<5||candidate.latitude===null} onClick={()=>{onChange({...candidate,confirmed:true});close();}}>تأیید نقطه و آدرس</button><button type="button" onClick={close}>انصراف؛ ادامه با آدرس دستی</button></div></dialog>}
 </section>;
}
