import initSqlJs from 'sql.js';
import { handlePilot } from '../lib/pilot/service';
import type { Settings } from '../lib/pilot/config';
import { BrowserDatabase, browserFiles, openStore } from './storage';
import schema from '../drizzle-pilot/0000_optimal_wind_dancer.sql';
import guards from '../drizzle-pilot/0001_guards.sql';

export async function createDemoBackend() {
  if (!window.isSecureContext || !crypto.subtle || !navigator.locks) {
    throw new Error('نمایش را با آدرس HTTPS و مرورگر به‌روز باز کنید.');
  }
  const base = new URL('.', document.baseURI);
  const namespace = `salamatban-presentation-v1:${base.pathname}`;
  const sessionKey = `${namespace}:session`;
  const SQL = await initSqlJs({ locateFile: () => new URL('sql-wasm.wasm', base).href });
  const store = await openStore(namespace);
  const settings: Settings = {
    mode: 'demo', origin: location.origin, authSecret: 'browser-demo-only-no-real-accounts',
    merchant: '', smsKey: '', smsTemplate: '', staffTotp: {}, priceRial: 12000000,
    pricingVersion: 'demo-price', scanUrl: '', scanToken: '', consentVersion: '', consentBody: '',
    clinicalApproved: false, ready: false,
  };
  const responseError = () => Response.json({ error: 'DEMO_STORAGE_FAILED' }, { status: 503 });
  const execute: typeof fetch = async (input, init) => {
    const url = new URL(input instanceof Request ? input.url : String(input), location.origin);
    if (url.origin !== location.origin || !url.pathname.startsWith('/api/pilot/')) {
      throw new Error('Only local presentation requests are supported.');
    }
    return navigator.locks.request(namespace, async () => {
      let database: BrowserDatabase | undefined;
      try {
        const saved = await store.read();
        database = new BrowserDatabase(SQL, saved?.database);
        if (!saved) { database.sqlite.run(schema); database.sqlite.run(guards); }
        const files = saved?.files ?? {};
        const headers = new Headers(init?.headers);
        headers.set('Origin', location.origin);
        const cookie = sessionStorage.getItem(sessionKey);
        if (cookie) headers.set('Cookie', cookie);
        const request = new Request(url, { ...init, headers });
        // A real browser Request filters Cookie/Origin. This object never leaves
        // the browser: provide those headers to the in-process service explicitly.
        // Retain the multipart boundary generated by Request for uploaded files.
        const localHeaders = new Headers(request.headers);
        headers.forEach((value, key) => localHeaders.set(key, value));
        Object.defineProperty(request, 'headers', { value: localHeaders });
        const response = await handlePilot(request, {
          db: database as unknown as D1Database,
          files: browserFiles(files) as unknown as R2Bucket,
          c: settings,
        });
        await store.write({ database: database.sqlite.export(), files });
        const newCookie = response.headers.get('Set-Cookie');
        if (newCookie) {
          if (newCookie.includes('Max-Age=0')) sessionStorage.removeItem(sessionKey);
          else sessionStorage.setItem(sessionKey, newCookie.split(';')[0]);
        }
        return response;
      } catch (error) {
        console.error('Demo storage error', error);
        return responseError();
      } finally { database?.sqlite.close(); }
    });
  };
  return {
    fetch: execute,
    async reset() {
      await navigator.locks.request(namespace, () => store.clear());
      sessionStorage.removeItem(sessionKey);
      location.reload();
    },
    async downloadFile(id: string, name: string) {
      const response = await execute(`/api/pilot/files/${encodeURIComponent(id)}`);
      if (!response.ok) throw new Error('مدرک در این حساب قابل دریافت نیست.');
      const href = URL.createObjectURL(await response.blob());
      const link = document.createElement('a');
      link.href = href; link.download = name; link.click();
      setTimeout(() => URL.revokeObjectURL(href), 1000);
    },
  };
}
