import {useEffect,useRef,useState} from 'react';
import { createRoot } from 'react-dom/client';
import Pilot from '../app/pilot/pilot';
import {Icon,BrandMark} from '../app/pilot/brand';
import { createDemoBackend, type DemoLane } from './backend';
import {demoCases,completeAccounts} from './fixtures';
import './presentation.css';
import '../app/pilot/pilot.css';
import '../app/pilot/visual-language.css';
import '../app/pilot/login-layout.css';
import {DemoAccountPeek,type DemoSample} from '../app/pilot/demo-account-peek';

declare const __SALAMATBAN_MAPS_GATEWAY_URL__: string | null;
type Backend=Awaited<ReturnType<typeof createDemoBackend>>;
const laneKey=`salamatban-selected-lane:${new URL('.',document.baseURI).pathname}`;
const choiceKey=`salamatban-entry-choice:${new URL('.',document.baseURI).pathname}`;
function chosenLane():DemoLane{try{const explicit=new URLSearchParams(location.search).get('lane');return explicit==='practice'||explicit==='complete'?explicit:localStorage.getItem(laneKey)==='complete'?'complete':'practice';}catch{return 'practice';}}
function hasEntryChoice(){const query=new URLSearchParams(location.search);if(['practice','complete'].includes(query.get('lane')||'')||query.get('demo')==='after-payment')return true;try{return ['practice','complete'].includes(localStorage.getItem(choiceKey)||'');}catch{return false;}}
const entryOptions=[{lane:'practice' as const,icon:'route',title:'خودم تست کنم',hint:'یک سناریو را از ابتدا بسازید و با نقش‌های مختلف جلو ببرید.',tag:'حساب‌های تست · شروع از ابتدا'},{lane:'complete' as const,icon:'file',title:'نمونه‌های کامل را ببینم',hint:'پرونده‌ها، برنامه‌ها و پیگیری‌های آماده را در نقش‌های مختلف ببینید.',tag:'۱۰ عضو فرضی · سابقه و مدارک آماده'}];
function EntryModes({lane,busy,onChoose,first=false}:{lane:DemoLane;busy:boolean;onChoose:(lane:DemoLane)=>void;first?:boolean}){return <section className={`entry-modes ${first?'entry-modes-first':''}`} aria-label="انتخاب روش تجربه">{entryOptions.map(option=><button type="button" key={option.lane} disabled={busy} aria-pressed={!first&&lane===option.lane} onClick={()=>onChoose(option.lane)}><span className="entry-mode-icon"><Icon name={option.icon} size={first?28:21}/></span><span className="entry-mode-copy"><strong>{option.title}</strong><small>{first?option.hint:option.tag}</small>{first&&<em>{option.tag}</em>}</span><Icon name={!first&&lane===option.lane?'check':'arrow'} size={20}/></button>)}</section>;}
// The static entry uses a preoptimized local WebP with reserved dimensions; no Next image server is deployed.
/* eslint-disable @next/next/no-img-element */
function EntryChoice({lane,busy,onChoose}:{lane:DemoLane;busy:boolean;onChoose:(lane:DemoLane)=>void}){return <main className="entry-choice"><header><BrandMark/><span>سلامت‌بان · تجربهٔ محصول</span></header><div className="entry-choice-content"><section><span className="demo-eyebrow">دو راه برای آشنایی با سلامت‌بان</span><h1>چطور می‌خواهید<br/>تجربه‌اش کنید؟</h1><p>خودتان یک مسیر بسازید، یا نتیجهٔ مسیرهای آماده را ببینید.</p><EntryModes lane={lane} busy={busy} onChoose={onChoose} first/><small className="entry-choice-note"><Icon name="shield" size={16}/>هر دو فضا نمایشی‌اند؛ اطلاعات و پرداخت‌ها ساختگی‌اند.</small></section><div className="entry-choice-photo"><img src="./media/care-consultation.webp" alt="گفت‌وگوی حرفه‌ای تیم مراقبت" width="1200" height="900"/><div><Icon name="heart" size={24}/><span>از اولین قدم، تا همراهی در ادامهٔ مسیر.</span></div></div></div></main>;}
/* eslint-enable @next/next/no-img-element */
function rememberLane(lane:DemoLane){try{localStorage.setItem(laneKey,lane);localStorage.setItem(choiceKey,lane);}catch{}const url=new URL(location.href);url.searchParams.delete('lane');history.replaceState(null,'',url);}
const stateNames:Record<string,string>={completed:'دوره کامل‌شده',active:'در حال پیگیری',submitted:'در انتظار پزشک',needs_information:'نیاز به مدرک کامل‌تر',draft:'پیش از پرداخت',urgent:'گزارش علامت هشدار'};
const fa=(n:number)=>n.toLocaleString('fa-IR');
function CaseCatalog({busy,onEnter,onPreview,backend}:{busy:boolean;onEnter:(phone:string)=>void;onPreview:()=>void;backend:Backend}){
 const [samples,setSamples]=useState<DemoSample[]>([]);
 useEffect(()=>{let active=true;void backend.fetch('/api/pilot/meta').then(r=>r.json() as Promise<{samples:DemoSample[]}>).then(v=>{if(active)setSamples(v.samples||[]);}).catch(()=>{});return()=>{active=false;};},[backend]);
 const storyFor=(person:typeof demoCases[number])=>samples.find(s=>s.phone===person.phone)?.story;
 const progressFor=(person:typeof demoCases[number])=>storyFor(person)?.progressPercent??person.initialProgress;
 const countFor=(person:typeof demoCases[number],label:string,fallback:number)=>storyFor(person)?.metrics.find(m=>m.label===label)?.value??fallback;
 return <main className="demo-catalog"><div className="demo-catalog-heading"><div><span className="demo-eyebrow">۱۰ عضو فرضی · یک گردش کار قابل تجربه</span><h1>برای ارائه، از یک داستان شروع کنید.</h1><p>سه عضو با سابقه یک سال، سه دوره کامل‌شده و سه برنامه در حال پیگیری؛ از حساب عضو تا میز کار پزشک، کارشناس و مدیر.</p></div><BrandMark/></div><div className="demo-role-entry"><div><strong>پشت صحنهٔ همین پرونده‌ها</strong><p>در این فضا می‌توانید اقدام‌ها را ادامه دهید. تغییرات فقط در همین مرورگر می‌مانند.</p></div>{completeAccounts.filter(a=>a.role!=='member').map(account=><DemoAccountPeek key={account.phone} sample={samples.find(s=>s.phone===account.phone)} className="demo-staff-peek">{descriptionId=><button className="p-secondary" aria-describedby={descriptionId} disabled={busy} onClick={()=>onEnter(account.phone)}><Icon name={account.role==='clinician'?'doctor':account.role==='coordinator'?'calendar':'settings'} size={18}/>{account.name}</button>}</DemoAccountPeek>)}</div><section className="demo-case-grid" aria-label="پرونده‌های فرضی">{demoCases.map(person=><DemoAccountPeek key={person.id} sample={samples.find(s=>s.phone===person.phone)} className="demo-case-peek">{descriptionId=><article className="demo-case" aria-describedby={descriptionId}><header><span className="demo-case-avatar">{person.name.slice(0,1)}</span><div><h2>{person.name}</h2><small>{person.profile.city} · {person.ageDays>=365?'سابقهٔ یک سال':person.ageDays===60?'دو ماه':person.ageDays===7?'یک هفته':`${fa(person.ageDays)} روز`}</small></div><span className="demo-case-state">{storyFor(person)?.status||stateNames[person.state]}</span></header><p className="demo-case-goal">{person.profile.goal}</p><p>{person.story}</p><div className="demo-case-measures"><span><b>{fa(countFor(person,'نسخهٔ برنامه',person.plans.length))}</b> نسخه برنامه</span><span><b>{fa(countFor(person,'مدرک',person.documents.length))}</b> مدرک</span><span><b>{progressFor(person)===null?'—':`${fa(progressFor(person)??0)}٪`}</b> دورهٔ جاری</span></div>{progressFor(person)!==null&&<div className="demo-case-bar"><span style={{width:`${progressFor(person)}%`}}/></div>}<button className="p-primary" disabled={busy} onClick={()=>onEnter(person.phone)}>ورود به پروندهٔ {person.profile.firstName}<Icon name="arrow" size={17}/></button></article>}</DemoAccountPeek>)}</section><aside className="demo-catalog-foot"><p>نقطهٔ شروع سناریوها ۱۶ مهر ۱۴۰۵ است؛ شاخص‌ها و کارت معرفی، آخرین وضعیت ذخیره‌شدهٔ همین فضای دمو را نشان می‌دهند. درصدها شمارش اقدام‌ها هستند، نه نمره سلامت. اسناد، نام‌ها، پرداخت‌ها و مراکز هماهنگی این ده پرونده ساختگی‌اند.</p><button className="p-secondary" disabled={busy} onClick={onPreview}>مشاهده نمونه بعد از خرید، فقط خواندنی</button></aside></main>;
}
function PaidPreview({onClose}:{onClose:()=>void}){
 const [phone,PH]=useState(demoCases.find(p=>p.preview)!.phone),[backend,B]=useState<Backend|null>(null),[error,E]=useState('');
 const title=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{title.current?.focus();},[]);
 useEffect(()=>{let active=true;let instance:Backend|undefined;
  void (async()=>{instance=await createDemoBackend({lane:'complete',preview:true});await instance.enterSample(phone);if(active)B(instance);else instance.dispose();})().catch(e=>{if(active)E(e.message);});
  return()=>{active=false;instance?.dispose();};
 },[phone]);
 const person=demoCases.find(p=>p.phone===phone)!;
 return <section className="demo-preview preview-readonly" aria-label="نمونهٔ کامل بعد از پرداخت"><header className="demo-preview-bar"><div><h1 tabIndex={-1} ref={title}>نمونهٔ بعد از خرید · {person.name}</h1><p>اطلاعات فرضی · بازدید فقط‌خواندنی · پروندهٔ شما محفوظ است.</p></div><button className="p-secondary" onClick={onClose}><Icon name="arrow" size={18}/> بازگشت به پروندهٔ من</button></header><nav className="demo-preview-people" aria-label="انتخاب نمونه"><span>داستان دیگری را ببینید:</span>{demoCases.filter(p=>p.preview).map(p=><button key={p.phone} aria-pressed={p.phone===phone} onClick={()=>{if(p.phone===phone)return;B(null);E('');PH(p.phone);}}><Icon name={p.state==='completed'?'check':'route'} size={17}/>{p.name}<small>{p.state==='completed'?'دوره کامل‌شده':'در حال پیگیری'}</small></button>)}</nav>{error?<div className="demo-operation-error" role="alert"><p>{error}</p><button className="p-secondary" onClick={()=>{B(null);E('');PH(demoCases.find(p=>p.phone!==phone&&p.preview)!.phone);}}>تلاش با نمونهٔ دیگر</button></div>:backend?<Pilot key={phone} {...pilotProps(backend)} previewOnly mainId="paid-demo-main"/>:<div className="demo-loading" role="status"><BrandMark/><p>در حال آماده‌سازی نمونهٔ برنامه و مدارک…</p></div>}</section>;
}
function pilotProps(backend:Backend){return {transport:backend.fetch,hospitalLookupEndpoint:__SALAMATBAN_MAPS_GATEWAY_URL__,hospitalSnapshotUrl:'./data/care-facilities.geoapify.json',homeHref:'./',loginImageHref:'./media/care-consultation.webp',brandHref:'./brand/index.html',downloadFile:backend.downloadFile,saveMessage:'تغییرات در همین مرورگر ذخیره شد.'};}
function Presentation({initial,initialLane,initialAuthenticated}:{initial:Backend;initialLane:DemoLane;initialAuthenticated:boolean}){
 const [lane,L]=useState(initialLane),[backend,B]=useState(initial),[key,K]=useState(0),[catalog,CT]=useState(new URLSearchParams(location.search).get('lane')==='complete');
 const [busy,S]=useState(false),[error,E]=useState(''),[preview,P]=useState(new URLSearchParams(location.search).get('demo')==='after-payment');
 const [chosen,CH]=useState(hasEntryChoice()||initialAuthenticated),[authenticated,AU]=useState(initialAuthenticated);
 const cache=useRef<Partial<Record<DemoLane,Backend>>>({[initialLane]:initial});
 const beforeLeave=useRef<()=>Promise<boolean>>(async()=>true),returnFocus=useRef<HTMLElement|null>(null),returnScroll=useRef(0);
 const register=(guard:()=>Promise<boolean>)=>{beforeLeave.current=guard;};
 async function operation(run:()=>Promise<void>){if(busy)return;S(true);E('');try{if(!await beforeLeave.current()){E('تغییر فضا انجام نشد؛ ابتدا ذخیره پاسخ‌ها را در همین پرونده کامل کنید.');return;}await run();}catch(e){E((e as Error).message);}finally{S(false);}}
 function openPreview(){returnFocus.current=document.activeElement as HTMLElement;returnScroll.current=scrollY;P(true);window.scrollTo(0,0);}
 function closePreview(){P(false);requestAnimationFrame(()=>{window.scrollTo(0,returnScroll.current);returnFocus.current?.focus({preventScroll:true});});}
 async function switchLane(next:DemoLane){if(next===lane)return;await operation(async()=>{const instance=cache.current[next]||await createDemoBackend({lane:next});cache.current[next]=instance;await instance.fetch('/api/pilot/meta').then(async r=>{if(!r.ok)throw new Error('فضای دمو آماده نشد. اتصال و ذخیره‌سازی مرورگر را بررسی کنید.');});B(instance);L(next);CT(next==='complete');K(k=>k+1);beforeLeave.current=async()=>true;rememberLane(next);window.scrollTo(0,0);});}
 async function chooseEntry(next:DemoLane){if(chosen&&next===lane)return;await operation(async()=>{const instance=cache.current[next]||await createDemoBackend({lane:next});cache.current[next]=instance;const meta=await instance.fetch('/api/pilot/meta');if(!meta.ok)throw new Error('فضا آماده نشد؛ دوباره تلاش کنید.');const me=await instance.fetch('/api/pilot/me').then(r=>r.json() as Promise<{user:unknown;csrf:string}>);if(me.user){const logout=await instance.fetch('/api/pilot/auth/logout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me.csrf},body:'{}'});if(!logout.ok)throw new Error('تغییر حساب انجام نشد؛ دوباره تلاش کنید.');}AU(false);B(instance);L(next);CT(false);CH(true);K(k=>k+1);beforeLeave.current=async()=>true;rememberLane(next);window.scrollTo(0,0);});}
 async function enter(phone:string){await operation(async()=>{await backend.enterSample(phone);CT(false);K(k=>k+1);beforeLeave.current=async()=>true;window.scrollTo(0,0);});}
 return <><div className={`presentation-mode lane-${lane} ${chosen&&!authenticated&&!catalog?'presentation-entry':''}`} hidden={preview} inert={preview?true:undefined}><aside hidden={!chosen||(!authenticated&&!catalog)} className="presentation-note" aria-label="انتخاب فضای نمایش"><div className="presentation-lanes" role="group" aria-label="دو فضای مستقل"><button aria-pressed={lane==='practice'} disabled={busy} onClick={()=>void switchLane('practice')}>فضای ثبت و آزمون</button><button aria-pressed={lane==='complete'} disabled={busy} onClick={()=>void switchLane('complete')}>دموی کامل</button></div><p>{lane==='practice'?'ثبت از ابتدا · داده‌های ساختگی، فقط در همین مرورگر':'۱۰ پرونده ساختگی · مستقل از فضای آزمون'}</p><div className="presentation-tools">{lane==='complete'&&<button disabled={busy} onClick={()=>void operation(async()=>{CT(c=>!c);beforeLeave.current=async()=>true;})}>{catalog?'بازگشت به پنل':'فهرست پرونده‌ها و نقش‌ها'}</button>}<button disabled={busy} onClick={()=>{if(confirm(`فقط اطلاعات ${lane==='practice'?'فضای ثبت و آزمون':'دموی کامل'} پاک شود؟ ${lane==='complete'?'پرونده‌های اولیه دوباره ساخته می‌شوند.':'فضای دیگر دست‌نخورده می‌ماند.'}`))void backend.reset().catch(()=>E('پاک‌کردن این فضا انجام نشد.'));}}>بازنشانی این فضا</button></div></aside><div className="demo-operation-status" aria-live="polite">{busy?'در حال آماده‌سازی فضا…':error}</div>{!chosen?<EntryChoice lane={lane} busy={busy} onChoose={next=>void chooseEntry(next)}/>:catalog&&lane==='complete'?<CaseCatalog backend={backend} busy={busy} onEnter={phone=>void enter(phone)} onPreview={openPreview}/>:<Pilot key={`${lane}-${key}`} {...pilotProps(backend)} onPaidDemo={openPreview} onBeforeLeave={register} onAuthChange={AU} demoLane={lane} entryModeControl={<EntryModes lane={lane} busy={busy} onChoose={next=>void chooseEntry(next)}/>}/>}</div>{preview&&<PaidPreview onClose={closePreview}/>}</>;
}
async function main(){
 const lane=chosenLane();let timer:ReturnType<typeof setTimeout>|undefined;
 const backend=await Promise.race([createDemoBackend({lane}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('دریافت برنامه یا دسترسی به ذخیره‌سازی بیش از حد طول کشید.')),45000);})]).finally(()=>clearTimeout(timer));
 const me=await backend.fetch('/api/pilot/me').then(r=>r.json() as Promise<{user:unknown}>);
 // Do not paint interactive controls in a fallback font on a normal cold visit.
 // A bounded wait keeps the app usable if a font request fails; swap can recover later.
 await Promise.race([Promise.all([400,500,600,700,800,900].map(weight=>document.fonts.load(`${weight} 16px Peyda`))),new Promise(resolve=>setTimeout(resolve,4000))]).catch(()=>{});
 createRoot(document.getElementById('app')!).render(<Presentation initial={backend} initialLane={lane} initialAuthenticated={!!me.user}/>);
}
void main().catch((error:Error)=>{const root=document.getElementById('app')!;root.textContent=`نسخهٔ نمایشی بارگذاری نشد. ${error.message}`;root.setAttribute('role','alert');const retry=document.createElement('button');retry.textContent='تلاش دوباره';retry.onclick=()=>location.reload();root.appendChild(retry);});
