'use client';
import { useEffect, useId, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { LivingScene, SceneMotionControl } from './living-scene';
import { Icon } from './brand';
import './arrival.css';
type Props={policy:string;clinical:string;coordinationText:string;version:string;consent:boolean;coordination:boolean;busy:boolean;onConsent:(value:boolean)=>void;onCoordination:(value:boolean)=>void;onContinue:()=>void;onBack:()=>void};
export function ConsentIntro(props:Props){
 const [paused,setPaused]=useState(false);
 const [open,O]=useState<'policy'|'coordination'|null>(null),dialog=useRef<HTMLDialogElement>(null),opener=useRef<HTMLElement|null>(null),heading=useRef<HTMLHeadingElement>(null),id=useId();
 useEffect(()=>{heading.current?.focus({preventScroll:true});},[]);
 function show(kind:'policy'|'coordination'){opener.current=document.activeElement as HTMLElement;O(kind);}
 function close(){dialog.current?.close();O(null);opener.current?.focus();}
 return <section className="consent-intro"><div className="consent-visual"><LivingScene small surface="light" paused={paused}/><span className="consent-visual-caption">فضایی برای گفتن.<br/><strong>همراهی برای ادامه دادن.</strong></span><SceneMotionControl className="consent-motion" paused={paused} onChange={setPaused}/></div><div className="consent-copy"><span className="consent-kicker"><Icon name="shield" size={18}/> انتخاب با شماست</span><h1 ref={heading} tabIndex={-1}>با خیال راحت<br/>شروع کنیم.</h1><p>اطلاعات شما برای تشکیل پرونده و بررسی پزشک استفاده می‌شود.</p><div className="consent-choices"><div className="consent-choice"><label><input type="checkbox" checked={props.consent} disabled={props.busy} onChange={e=>props.onConsent(e.target.checked)} aria-label="پذیرش قوانین و بررسی پزشک"/><span><button type="button" className="consent-policy-link" aria-haspopup="dialog" onClick={e=>{e.preventDefault();show('policy');}}>قوانین و حریم خصوصی</button> را می‌پذیرم و با بررسی پزشک موافقم.</span></label></div><div className="consent-choice consent-optional"><label><input type="checkbox" checked={props.coordination} disabled={props.busy} onChange={e=>props.onCoordination(e.target.checked)} aria-label="تماس کارشناس برای هماهنگی نوبت"/><span>کارشناس برای هماهنگی نوبت با من تماس بگیرد. <small>اختیاری</small></span></label><button type="button" className="consent-policy-link" aria-haspopup="dialog" onClick={()=>show('coordination')}>جزئیات اجازهٔ تماس</button></div></div><div className="consent-actions"><button className="p-primary" disabled={props.busy||!props.consent} onClick={props.onContinue}>موافقم، ادامه بده <Icon name="arrow" size={19}/></button><button className="p-link" disabled={props.busy} onClick={props.onBack}>بازگشت</button></div></div>
 {open&&createPortal(<dialog className="consent-dialog" dir="rtl" aria-labelledby={`${id}-title`} ref={node=>{dialog.current=node;if(node&&!node.open)node.showModal();}} onKeyDown={event=>{if(event.key!=='Tab')return;const controls=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),[tabindex="0"]'));const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}} onCancel={event=>{event.preventDefault();close();}} onClick={event=>{if(event.target!==event.currentTarget)return;const r=event.currentTarget.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();}}><header><div><span>سلامت‌بان</span><h2 id={`${id}-title`}>{open==='policy'?'قوانین و حریم خصوصی':'اجازهٔ تماس کارشناس'}</h2></div><button autoFocus type="button" aria-label="بستن قوانین" onClick={close}><Icon name="close"/></button></header><div className="consent-document" tabIndex={0}>{open==='policy'?<><h3>استفاده از اطلاعات شما</h3><p>{props.policy}</p><h3>اجازهٔ بررسی پزشک</h3><p>{props.clinical}</p></>:<p>{props.coordinationText}</p>}<p className="consent-document-version">نسخهٔ متن: <bdi>{props.version}</bdi></p></div><footer><span>باز کردن این متن به‌معنای پذیرش آن نیست.</span><button type="button" onClick={close}>بازگشت به انتخاب من</button></footer></dialog>,document.body)}
 </section>;
}
