(()=>{
 const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
 const panes=$$('.pane');
 function navigate(focus=false){const key=location.hash.slice(1),pane=panes.find(p=>p.id===key)||panes[0];panes.forEach(p=>p.hidden=p!==pane);$$('[data-nav]').forEach(a=>{if(a.dataset.nav===pane.id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(focus){pane.querySelector('h2')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}}
 window.addEventListener('hashchange',()=>navigate(true));navigate();
 $$('[data-role]').forEach(b=>b.addEventListener('click',()=>{$$('[data-role]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('[data-role-panel]').forEach(p=>p.hidden=p.dataset.rolePanel!==b.dataset.role)}));
 $$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('[data-group]').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.group!==b.dataset.filter)}));
 const assets=JSON.parse($('#asset-catalog').textContent),dialog=$('#image-dialog'),img=$('#viewer-image');let zoom=1;
 function setZoom(value){zoom=Math.max(1,Math.min(3,value));img.style.width=`${zoom*100}%`;$('#zoom-out').disabled=zoom===1;$('#zoom-in').disabled=zoom===3;$('#zoom-reset').textContent=zoom===1?'اندازهٔ مناسب':`${Math.round(zoom*100)}٪`}
 $$('[data-view]').forEach(b=>b.addEventListener('click',()=>{const a=assets[b.dataset.view];$('#image-title').textContent=a.title;$('#image-description').textContent=a.description;img.src=a.png;img.alt=a.title;$('#download-png').href=a.png;$('#download-svg').hidden=!a.svg;if(a.svg)$('#download-svg').href=a.svg;setZoom(1);dialog.showModal();$('.viewer-scroll').scrollTo(0,0);$('#close-viewer').focus()}));
 $('#close-viewer').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
 $('#zoom-in').addEventListener('click',()=>setZoom(zoom+.5));$('#zoom-out').addEventListener('click',()=>setZoom(zoom-.5));$('#zoom-reset').addEventListener('click',()=>setZoom(1));
 const fields=['perspective','topic','comment'],key='salamatban-showcase-feedback',form=$('#feedback-form');let storageOK=true;
 try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&typeof saved==='object')fields.forEach(k=>{if(typeof saved[k]==='string')$('#'+k).value=saved[k].slice(0,4000)})}catch{storageOK=false}
 function updateDraft(){const draft=Object.fromEntries(fields.map(k=>[k,$('#'+k).value]));try{localStorage.setItem(key,JSON.stringify(draft));storageOK=true}catch{storageOK=false}$('#draft-status').textContent=storageOK?'پیش‌نویس در این مرورگر ذخیره شد؛ هنوز برای کسی ارسال نشده است.':'ذخیرهٔ محلی در این مرورگر ممکن نیست؛ پیش از بستن صفحه متن را کپی کنید.';$('#feedback-result').hidden=true}
 form.addEventListener('input',updateDraft);form.addEventListener('change',updateDraft);
 if(!storageOK)$('#draft-status').textContent='ذخیرهٔ محلی در دسترس نیست؛ پیش از بستن صفحه متن را کپی کنید.';
 form.addEventListener('submit',e=>{e.preventDefault();if(!$('#comment').value.trim()){$('#comment').setCustomValidity('لطفاً نظر یا پیشنهادتان را بنویسید.');$('#comment').reportValidity();return}$('#comment').setCustomValidity('');$('#feedback-output').value=`بازخورد دربارهٔ سلامت‌بان\nزاویهٔ بررسی: ${$('#perspective').value}\nبخش: ${$('#topic').value}\n\n${$('#comment').value.trim()}\n\nنسخهٔ معرفی: ۲٫۳`;$('#feedback-result').hidden=false;$('#feedback-result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('#feedback-output').focus({preventScroll:true})});
 $('#comment').addEventListener('input',()=>$('#comment').setCustomValidity(''));
 $('#copy-feedback').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#feedback-output').value);$('#export-status').textContent='متن کپی شد؛ حالا آن را برای سازنده ارسال کنید.'}catch{$('#feedback-output').focus();$('#feedback-output').select();$('#export-status').textContent='کپی خودکار ممکن نشد؛ متن انتخاب شده است. با فرمان کپی دستگاهتان آن را بردارید.'}});
 $('#download-feedback').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob(['\ufeff'+$('#feedback-output').value],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Salamatban-feedback.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#export-status').textContent='فایل متنی آمادهٔ دریافت شد؛ برای رساندن نظر، فایل را برای سازنده بفرستید.'});
})();
