"""Self-contained, file-friendly entrance to the complete delivery."""
import base64
import html
import json
from delivery_docs import VERSION, APP_VERSION, DOCS, page

ICONS={
 'grid':'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',
 'image':'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="2"/><path d="m3 17 5-5 4 4 4-6 5 7"/>',
 'message':'<path d="M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z"/><path d="M8 9h8m-8 4h5"/>',
 'close':'<path d="m6 6 12 12M6 18 18 6"/>',
 'arrow':'<path d="M20 12H4m6-6-6 6 6 6"/>',
 'book':'<path d="M12 5c-3-2-7-2-10-1v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1Zm0 0v15"/>',
 'code':'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',
 'route':'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M9 5h7a4 4 0 0 1 0 8H8a3 3 0 0 0 0 6h7"/>',
 'file':'<path d="M14 3H5v18h14V8l-5-5ZM14 3v5h5M8 12h8m-8 4h6"/>',
 'doctor':'<path d="M5 3v6a5 5 0 0 0 10 0V3M3 3h4m6 0h4M10 14v2a5 5 0 0 0 10 0v-3"/><circle cx="20" cy="10" r="2"/>',
 'check':'<path d="m5 12 4 4L19 6"/>',
 'download':'<path d="M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4"/>',
 'monitor':'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>',
 'chevron':'<path d="m6 9 6 6 6-6"/>',
}
def icon(name):return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+ICONS[name]+'</svg>'
def fa(s):return s.translate(str.maketrans('0123456789.','۰۱۲۳۴۵۶۷۸۹٫'))
def render(root):
 fonts=''.join('@font-face{font-family:Peyda;font-weight:'+weight+';font-display:swap;src:url(data:font/woff2;base64,'+base64.b64encode((root/'site/public/fonts'/f'PeydaWebFaNum-{name}.woff2').read_bytes()).decode()+')}' for name,weight in [('Regular','400'),('Bold','700')])
 css=fonts+(root/'scripts/delivery-template/landing.css').read_text()
 mark=(root/'site/public/brand/symbol.svg').read_text()
 live='https://ourgemeniprostudent-png.github.io/salamatban/?v='+APP_VERSION
 guide='documents/Salamatban-Complete-Guide-fa.html'
 diagrams=json.loads((root/'deliverables/showcase/diagrams.json').read_text())
 screens=[{'id':'welcome','title':'یک شروع تازه','description':'گرافیک زنده، واکنش به شروع و گفت‌وگوی بدون شلوغی.','png':'screen-welcome.png'}, {'id':'consent','title':'پذیرش کوتاه و روشن','description':'متن کامل قوانین پشت لینک؛ اجازهٔ تماس جدا و اختیاری.','png':'screen-consent.png'}, {'id':'home','title':'خانهٔ همراه شما','description':'وضعیت واقعی پرونده و قدم بعدی پس از انتشار پزشک.','png':'screen-home.png'}, {'id':'program','title':'برنامه و قدم‌های من','description':'جمع‌بندی پزشک و ثبت انجام در همان مسیر اقدام‌ها.','png':'screen-program.png'}, {'id':'form','title':'شروع از دلیل مراجعهٔ شما','description':'شش مسیر، اولویت کاربر و هدف‌گذاری پیش از تشکیل برنامه.','png':'screen-form.png'}, {'id':'payment','title':'پرداخت نمایشی و رسید','description':'مرور سفارش، نتیجهٔ پرداخت و رسید قابل پیگیری.','png':'screen-payment.png'}, {'id':'doctor','title':'میز بررسی پزشک','description':'پروندهٔ تخصیص‌یافته، بررسی و اقدام‌های بعدی.','png':'screen-doctor.png'}, {'id':'coordinator','title':'میز هماهنگی کارشناس','description':'درخواست‌های ارجاعی و ثبت نتیجهٔ هماهنگی.','png':'screen-coordinator.png'}]
 assets={}
 for item in screens+diagrams:assets[item['id']]={**item,'png':'presentation/assets/'+item['png'],**({'svg':'presentation/assets/'+item['svg']} if 'svg' in item else {})}
 nav=[('overview','grid','نمای کلی'),('experience','route','تجربهٔ محصول'),('gallery','image','تصاویر محیط'),('architecture','code','معماری سامانه'),('readiness','check','وضعیت اجرا'),('feedback','message','نظر شما')]
 def link(label,url,cls='button primary',ico='arrow'):return f'<a class="{cls}" href="{url}">{label}{icon(ico)}</a>'
 def heading(kicker,title,desc):return f'<div class="section-heading"><p class="eyebrow">{kicker}</p><h2 tabindex="-1">{title}</h2><p>{desc}</p></div>'
 def image_card(item,group=''):
  key=item['id'];kind='طرح هدف' if item.get('status')=='target' else 'کد سروری موجود' if item.get('status')=='server' else 'نسخهٔ نمایشی' if 'status' in item else 'تصویر نمونه'
  return f'<article class="visual-card" data-group="{group}"><button class="visual-open" data-view="{key}" aria-label="بزرگ‌نمایی {item["title"]}"><img src="{assets[key]["png"]}" alt="{item["title"]}" loading="lazy"><span class="enlarge">{icon("image")} بزرگ‌نمایی</span></button><div class="visual-copy"><span class="badge {"amber" if item.get("status")=="target" else "soft"}">{kind}</span><h3>{item["title"]}</h3><p>{item["description"]}</p><div class="visual-links"><button data-view="{key}">مشاهدهٔ تصویر {icon("arrow")}</button>'+ (f'<a href="{assets[key]["png"]}" download>PNG</a><a href="{assets[key]["svg"]}" download>SVG</a>' if 'svg' in item else '')+'</div></div></article>'
 body='<a class="skip" href="#main">رفتن به محتوا</a><div class="dashboard"><aside class="sidebar"><a class="brand" href="#overview">'+mark+'<span>سلامت‌بان<small>معرفی و بررسی محصول</small></span></a><p class="nav-caption">مسیر آشنایی</p><nav aria-label="بخش‌های داشبورد">'
 for key,ico,title in nav:body+=f'<a href="#{key}" data-nav="{key}">{icon(ico)}<span>{title}</span>'+('<span class="nav-count">۶</span>' if key=='architecture' else '')+'</a>'
 body+='</nav><div class="sidebar-bottom"><p>خودتان تجربه کنید</p>'+link('مشاهدهٔ محصول',live)+f'<a class="quiet-link" href="{guide}">{icon("book")} راهنمای کوتاه</a><span class="sidebar-note">نمایش با اطلاعات ساختگی</span></div></aside><div class="workspace"><header class="topbar"><span><span class="status-dot"></span>فضای معرفی سلامت‌بان</span><div>'+link('راهنمای PDF','documents/Salamatban-Complete-Guide-fa.pdf','top-link','download')+link('نظر بدهید','#feedback','button small secondary','message')+'</div></header><main id="main">'
 body+='<section id="overview" class="pane">'+heading('از ایده تا تجربهٔ قابل بررسی','یک نگاه به سلامت‌بان','محصول را ببینید، مسیر کار را امتحان کنید و نظرتان را بگویید.')
 body+='<div class="overview-grid"><article class="intro-card"><span class="badge soft">پرونده · بررسی · پیگیری</span><h1>مسیر مراقبت،<br><em>روشن و قابل پیگیری.</em></h1><p>از گفت‌وگو دربارهٔ نیاز و هدف شما تا برنامهٔ پزشک و هماهنگی اقدام‌ها؛ سلامت‌بان این مسیر را برای عضو و تیم مراقبت کنار هم قرار می‌دهد.</p><div class="actions">'+link('تجربهٔ نسخهٔ نمایشی',live)+link('از کجا شروع کنم؟','#experience','button secondary','route')+'</div><div class="role-strip"><span>عضو</span><b>←</b><span>پزشک</span><b>←</b><span>کارشناس</span></div></article><article class="review-card"><div class="card-icon">'+icon('message')+'</div><h3>این‌جا برای نظر شماست</h3><p>لازم نیست همهٔ جزئیات فنی را بخوانید. از بخشی شروع کنید که برایتان مهم‌تر است.</p><a href="#gallery">ظاهر و تجربهٔ کاربری '+icon('arrow')+'</a><a href="#architecture">ساختار و معماری '+icon('arrow')+'</a><a href="#feedback">ابهام‌ها و پیشنهادها '+icon('arrow')+'</a></article></div>'
 body+='<div class="overview-lower"><article class="preview-card"><div class="panel-heading"><div><span class="eyebrow">از داخل محصول</span><h3>یک محیط، نقش‌های مشخص</h3></div><a href="#gallery">همهٔ تصاویر '+icon('arrow')+'</a></div><button class="product-preview" data-view="doctor" aria-label="بزرگ‌نمایی تصویر محیط پزشک"><img src="presentation/assets/screen-doctor.png" alt="نمونهٔ محیط بررسی پرونده توسط پزشک"><span>دیدن تصویر کامل '+icon('image')+'</span></button></article><article class="map-card"><span class="eyebrow">پشت صحنهٔ محصول</span><h3>معماری، در معرض دید</h3><p>از اجرای مرورگری تا طرح توسعهٔ سرور و دیتابیس؛ هر نمودار با وضعیت خودش مشخص شده است.</p><div class="mini-stack"><span>رابط و نقش‌ها</span><i>↓</i><span>منطق پرونده و پیگیری</span><i>↓</i><span>ذخیره‌سازی و سرویس‌ها</span></div>'+link('دیدن ۶ نمودار','#architecture','button secondary','code')+'</article></div><div class="inline-note">'+icon('check')+'<p>گردش‌های اصلی برای نمایش ساخته شده‌اند. اتصال پیامک، بانک و مراکز واقعی هنوز راه‌اندازی نشده است. <a href="#readiness">وضعیت اجرا را ببینید</a>.</p></div></section>'
 body+='<section id="experience" class="pane"><div class="inline-note"><p><strong>نقشهٔ جامع مسیر کاربر</strong> · <a href="presentation/assets/user-flow/index.html">باز کردن فلوچارت تصویری و بزرگ‌نمایی</a><br>این تصویر طرح هدف کامل است؛ محدودهٔ اجراشدهٔ نسخهٔ ۲٫۱ در راهنمای محصول مشخص شده است.</p></div>'+heading('چند دقیقه با محصول','مسیر هر نقش را امتحان کنید','یک پرونده را در همان مرورگر دنبال کنید؛ خروج از حساب، دادهٔ نمونه را پاک نمی‌کند.')+'<div class="role-tabs" role="group" aria-label="انتخاب نقش">'
 roles=[('member','عضو','09000000001',['با حساب عضو وارد شوید؛ کد نمایشی پس از درخواست روی صفحه است.','شروع آشنایی را بزنید؛ دلیل مراجعه، هدف، مشخصات و پاسخ‌های نمونه را ثبت کنید.','پرداخت نمایشی و سپس ارسال پرونده را انجام دهید.','برنامه و نتیجهٔ هماهنگی را بعد از اقدام تیم ببینید.'],'آیا قدم بعدی و وضعیت پرونده برایتان روشن است؟'),('doctor','پزشک','09000000011',['در همان مرورگر با حساب پزشک وارد شوید.','پروندهٔ تخصیص‌یافته را از صف انتخاب کنید.','اطلاعات بیشتری بخواهید یا جمع‌بندی و برنامه منتشر کنید.','اقدام‌های مربوط به تیم را با رضایت عضو به هماهنگی ارجاع دهید.'],'آیا بررسی پرونده و اقدام بعدی پزشک به اندازهٔ کافی واضح است؟'),('coordinator','کارشناس','09000000012',['ابتدا یک اقدام تیمی از سمت پزشک یا درخواست نوبت از عضو ایجاد کنید.','با حساب کارشناس وارد شوید و درخواست را از صف انتخاب کنید.','مرکز، زمان، مرجع تأیید و رضایت لازم را ثبت کنید.','نتیجهٔ هماهنگی یا انجام اقدام را برای عضو ثبت کنید.'],'آیا درخواست ارجاعی و مراحل هماهنگی قابل فهم است؟'),('admin','مدیر','09000000013',['با حساب مدیر وارد شوید.','اعضا و پزشک مسئول هر عضو را بررسی کنید.','دعوت، تخصیص و تعلیق دسترسی را با دادهٔ ساختگی امتحان کنید.','درخواست پشتیبانی را پاسخ دهید؛ حذف یا بازپرداخت واقعی هنوز اجرا نمی‌شود.'],'آیا مدیریت دسترسی و پیگیری درخواست‌ها روشن است؟')]
 for key,title,phone,steps,prompt in roles:body+=f'<button data-role="{key}" aria-pressed="{str(key=="member").lower()}">{title}</button>'
 body+='</div>'
 for key,title,phone,steps,prompt in roles:
  body+=f'<article class="role-panel" data-role-panel="{key}"'+(' hidden' if key!='member' else '')+f'><div><span class="badge soft">مسیر {title}</span><h3>با نقش {title} چه چیزی ببینم؟</h3><ol class="walkthrough">'+''.join(f'<li><span>{fa(str(i+1))}</span><p>{s}</p></li>' for i,s in enumerate(steps))+f'</ol></div><aside class="try-box"><span>حساب نمونهٔ {title}</span><bdi>{phone}</bdi><p>در فرم ورود، حساب نمونه را انتخاب کنید. کد نمایشی با کلیک روی کد یا آیکون کنارش کپی می‌شود.</p>'+link('باز کردن محصول',live)+f'<div class="review-prompt"><strong>هنگام بررسی به این فکر کنید</strong><p>{prompt}</p><a href="#feedback">نوشتن نظر {icon("arrow")}</a></div></aside></article>'
 body+='<details class="notice-details"><summary>اگر پرداخت متوقف بود یا صف کارشناس خالی بود چه کنم؟</summary><p>هشدار ثبت‌شده پیش از پرداخت به بررسی پزشک نیاز دارد. در حساب پزشک، پرونده را انتخاب و با یادداشت «ثبت بررسی انسانی علامت هشدار» را انجام دهید؛ سپس به عضو برگردید. کارشناس فقط درخواست‌های هماهنگی یا اقدام‌های ارجاع‌شده را می‌بیند، نه همهٔ پرونده‌های پزشکی.</p></details></section>'
 body+='<section id="gallery" class="pane">'+heading('تصاویر واقعی از سناریوهای نمونه','محیط محصول را ببینید','روی هر تصویر بزنید تا با اندازهٔ بزرگ‌تر بررسی کنید. داده‌های نمایش ساختگی‌اند.')+'<div class="gallery-grid">'+''.join(image_card(s) for s in screens)+'</div></section>'
 body+='<section id="architecture" class="pane">'+heading('معماری قابل مشاهده و دانلود','سامانه چطور ساخته شده است؟','نمودارهای اجرای فعلی و طرح آینده جدا مشخص‌اند. هر تصویر را بزرگ کنید یا فایل آن را بگیرید.')+'<div class="filter-row" role="group" aria-label="فیلتر نمودار"><button data-filter="all" aria-pressed="true">همهٔ نمودارها</button><button data-filter="current" aria-pressed="false">اجرا و کد موجود</button><button data-filter="target" aria-pressed="false">طرح توسعه</button></div><div class="diagram-grid">'+''.join(image_card(s,'target' if s['status']=='target' else 'current') for s in diagrams)+'</div><p class="subtle-note">طرح PostgreSQL هنوز روی برنامه اعمال نشده است؛ مدل آدرس و اتصال اقدام به کار به تکمیل نیاز دارد. فایل‌های PNG و SVG در پوشهٔ presentation/assets بسته هم موجودند.</p></section>'
 body+='<section id="readiness" class="pane">'+heading('تصویر روشن از وضعیت فعلی','چه چیزی ساخته شده، چه چیزی باقی است؟','قابلیت قابل نمایش با خدمت واقعی راه‌اندازی‌شده یکسان نیست.')+'<div class="readiness-grid"><article class="status-card ready"><span class="badge green">قابل اجرا در نمایش</span><h3>آنچه می‌توانید بررسی کنید</h3><ul>'+''.join('<li>'+icon('check')+x+'</li>' for x in ['ورود و دسترسی چهار نقش','فرم، ذخیرهٔ پاسخ و بارگذاری مدرک','پرداخت نمایشی و رسید','بررسی پزشک و انتشار برنامه','ارجاع، هماهنگی و نتیجهٔ اقدام','دعوت، تخصیص و پاسخ پشتیبانی'])+'</ul></article><article class="status-card pending"><span class="badge amber">پیش از استفادهٔ واقعی</span><h3>آنچه هنوز لازم است</h3><ul>'+''.join('<li>'+icon('route')+x+'</li>' for x in ['زیرساخت مشترک و پایگاه دادهٔ عملیاتی','پیامک، درگاه و اتصال واقعی مراکز','قیمت، قرارداد و رویهٔ بازپرداخت','تأیید محتوا و مسئولیت‌های بالینی','پشتیبان، بازیابی و عملیات حریم خصوصی','آزمون دستگاه واقعی، بار و امنیت'])+'</ul></article></div><div class="inline-note">'+icon('file')+'<p>آزمون‌های ثبت‌شدهٔ برنامه با دادهٔ ساختگی انجام شده‌اند. <a href="technical/ux-release.json">گزارش آزمون</a> و <a href="technical/FLOW-REVIEW-v1.7-fa.md">محدودهٔ بررسی</a> برای مرور دقیق‌تر در دسترس‌اند.</p></div><details class="notice-details"><summary>منابع فنی و کاربرگ‌های تکمیلی</summary><div class="resource-links">'
 for label,url in [('ساختار فنی و اجرا','technical/DEVELOPER-HANDOFF-fa.md'),('طرح دیتابیس هدف','technical/architecture/database-1000-users-fa.md'),('SQL هدف','technical/architecture/postgresql-target-schema.sql'),('نیازهای راه‌اندازی','technical/FIRST-OPERATIONAL-RELEASE-fa.md'),('کاربرگ آمادگی','technical/launch-readiness-register.csv'),('کاربرگ بودجه','technical/launch-budget.csv')]:body+=f'<a href="{url}">{label}{icon("arrow")}</a>'
 body+='</div></details></section>'
 body+='<section id="feedback" class="pane">'+heading('نظر شما مسیر بعدی را مشخص می‌کند','چه چیزی بهتر شود؟','یک نظر مشخص، از یک امتیاز کلی مفیدتر است. صفحه، ابهام و پیشنهادتان را بنویسید.')+'<div class="feedback-layout"><form id="feedback-form"><label for="perspective">از چه زاویه‌ای محصول را دیدید؟</label><select id="perspective" name="perspective"><option>کاربر محصول</option><option>پزشک یا تیم مراقبت</option><option>طراحی و تجربهٔ کاربری</option><option>فنی و معماری</option><option>نگاه کلی</option></select><label for="topic">دربارهٔ کدام بخش؟</label><select id="topic" name="topic"><option>تجربهٔ کلی</option><option>فرم و پرداخت</option><option>مسیر پزشک و کارشناس</option><option>ظاهر و راهنما</option><option>معماری سامانه</option></select><label for="comment">نظر و پیشنهاد شما <span>ضروری</span></label><textarea id="comment" name="comment" rows="7" maxlength="4000" required placeholder="در صفحهٔ ... انتظار داشتم ... اما ...؛ پیشنهاد من ..."></textarea><p class="field-note">اطلاعات شخصی یا پزشکی ننویسید.</p><div class="actions"><button type="submit" class="button primary">آماده‌کردن بازخورد '+icon('message')+'</button></div><p id="draft-status" class="field-note" role="status">پیش‌نویس فقط در این مرورگر نگه داشته می‌شود؛ ارسال خودکار ندارد.</p></form><aside class="feedback-help"><div class="card-icon">'+icon('message')+'</div><h3>سه سؤال برای شروع</h3><ol><li>کدام بخش برایتان روشن و مفید بود؟</li><li>کجا مکث کردید یا گیج شدید؟</li><li>اولین تغییری که پیشنهاد می‌کنید چیست؟</li></ol><p>پس از آماده‌کردن متن، آن را کپی کنید یا فایل بگیرید و از مسیر ارتباطی خودتان برای سازنده بفرستید.</p><a href="#experience">یک بار مسیر محصول را مرور کنید '+icon('arrow')+'</a></aside></div><section id="feedback-result" class="feedback-result" hidden><h3>متن آمادهٔ ارسال</h3><textarea id="feedback-output" readonly rows="8" aria-label="متن آمادهٔ بازخورد"></textarea><div class="actions"><button type="button" id="copy-feedback" class="button primary">کپی متن</button><button type="button" id="download-feedback" class="button secondary">دریافت فایل متنی '+icon('download')+'</button></div><p id="export-status" role="status">متن آماده شد؛ هنوز برای کسی ارسال نشده است.</p></section></section>'
 body+='</main><footer><span>سلامت‌بان · برای دیدن، تجربه‌کردن و بهترشدن</span><a href="'+guide+'">راهنمای کوتاه</a><details><summary>اجرای محلی</summary><p>برای دیدن این داشبورد فقط index.html را باز کنید. اجرای برنامهٔ داخل بسته به Python 3 نیاز دارد: <code>python3 serve-demo.py</code>. <a href="Start-Windows.cmd">ویندوز</a> · <a href="Start-Mac-Linux.command">مک/لینوکس</a></p></details></footer></div></div>'
 body+='<dialog id="image-dialog" aria-labelledby="image-title"><div class="viewer-header"><div><h2 id="image-title"></h2><p id="image-description"></p></div><button type="button" id="close-viewer" class="icon-button" aria-label="بستن تصویر">'+icon('close')+'</button></div><div class="viewer-tools"><button id="zoom-out" type="button" aria-label="کوچک‌نمایی">−</button><button id="zoom-reset" type="button">اندازهٔ مناسب</button><button id="zoom-in" type="button" aria-label="بزرگ‌نمایی بیشتر">+</button><a id="download-png" download>دریافت PNG</a><a id="download-svg" download>دریافت SVG</a></div><div class="viewer-scroll"><img id="viewer-image" alt=""></div></dialog>'
 script=(root/'scripts/delivery-template/dashboard.js').read_text()
 body+='<script type="application/json" id="asset-catalog">'+json.dumps(assets,ensure_ascii=False).replace('<','\\u003c')+'</script><script>'+script+'</script>'
 return page('سلامت‌بان | داشبورد معرفی محصول',body,css).replace('<main>','<div class="page-root">',1).replace('</main></body>','</div></body>')
