-- Salamatban target design, PostgreSQL 17. This is NOT an applied migration.
-- Run only in an empty disposable database for design validation.
-- UUIDs are generated by the application. No PostgreSQL extension is required.
-- Production role provisioning, authorization, transition rules, retention,
-- row-lock protocols and append-only grants are specified in database-1000-users-fa.md.
BEGIN;

CREATE TABLE app_users (
  id uuid PRIMARY KEY,
  phone_e164 varchar(16) UNIQUE,
  display_name varchar(140) NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  pseudonymized_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (phone_e164 IS NULL OR phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  CHECK (phone_e164 IS NOT NULL OR pseudonymized_at IS NOT NULL)
);

CREATE TABLE user_roles (
  user_id uuid NOT NULL REFERENCES app_users(id),
  role text NOT NULL CHECK (role IN ('member','clinician','coordinator','admin')),
  granted_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE service_capacity (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  enabled_member_limit integer NOT NULL CHECK (enabled_member_limit BETWEEN 1 AND 1000000),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO service_capacity (enabled_member_limit) VALUES (1000);

CREATE TABLE memberships (
  member_id uuid PRIMARY KEY,
  member_role text NOT NULL DEFAULT 'member' CHECK (member_role = 'member'),
  enabled boolean NOT NULL DEFAULT true,
  invited_by uuid REFERENCES app_users(id),
  invited_at timestamptz NOT NULL DEFAULT now(),
  first_activated_at timestamptz,
  disabled_at timestamptz,
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  FOREIGN KEY (member_id, member_role) REFERENCES user_roles(user_id, role),
  CHECK (enabled = (disabled_at IS NULL))
);
CREATE INDEX memberships_enabled ON memberships (member_id) WHERE enabled;

CREATE TABLE care_assignments (
  id uuid PRIMARY KEY,
  member_id uuid NOT NULL REFERENCES memberships(member_id),
  clinician_id uuid NOT NULL,
  clinician_role text NOT NULL DEFAULT 'clinician' CHECK (clinician_role = 'clinician'),
  assigned_by uuid REFERENCES app_users(id),
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  reason varchar(1000),
  FOREIGN KEY (clinician_id, clinician_role) REFERENCES user_roles(user_id, role),
  CHECK (ended_at IS NULL OR ended_at >= started_at)
);
CREATE UNIQUE INDEX care_assignment_current ON care_assignments (member_id) WHERE ended_at IS NULL;
CREATE INDEX care_assignment_queue ON care_assignments (clinician_id, member_id) WHERE ended_at IS NULL;

CREATE TABLE auth_otp_challenges (
  id uuid PRIMARY KEY,
  phone_e164 varchar(16) NOT NULL,
  digest char(64) NOT NULL CHECK (digest ~ '^[a-f0-9]{64}$'),
  attempts smallint NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > created_at)
);
CREATE INDEX otp_phone_created ON auth_otp_challenges (phone_e164, created_at DESC);
CREATE INDEX otp_expiration ON auth_otp_challenges (expires_at);

CREATE TABLE auth_sessions (
  digest char(64) PRIMARY KEY CHECK (digest ~ '^[a-f0-9]{64}$'),
  user_id uuid NOT NULL,
  active_role text NOT NULL,
  csrf_token char(64) NOT NULL,
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  mfa_verified_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (user_id, active_role) REFERENCES user_roles(user_id, role),
  CHECK (expires_at > created_at)
);
CREATE INDEX auth_session_user ON auth_sessions (user_id);
CREATE INDEX session_expiration ON auth_sessions (expires_at);

CREATE TABLE rate_limit_buckets (
  key_digest char(64) PRIMARY KEY CHECK (key_digest ~ '^[a-f0-9]{64}$'),
  count integer NOT NULL CHECK (count >= 0),
  expires_at timestamptz NOT NULL
);
CREATE INDEX rate_limit_expiration ON rate_limit_buckets (expires_at);

CREATE TABLE consent_documents (
  id uuid PRIMARY KEY,
  scope text NOT NULL CHECK (scope IN ('clinical','coordination','center_disclosure')),
  version varchar(80) NOT NULL,
  body text NOT NULL,
  sha256 char(64) NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
  approved_at timestamptz NOT NULL,
  effective_at timestamptz NOT NULL,
  UNIQUE (scope, version)
);

CREATE TABLE consent_events (
  id uuid PRIMARY KEY,
  member_id uuid NOT NULL REFERENCES memberships(member_id),
  document_id uuid NOT NULL REFERENCES consent_documents(id),
  decision text NOT NULL CHECK (decision IN ('accepted','withdrawn')),
  center_identity varchar(250),
  disclosure_scope varchar(1000),
  channel text NOT NULL CHECK (channel IN ('member_ui','verified_staff','legacy_import')),
  recorded_by uuid REFERENCES app_users(id),
  evidence_reference varchar(250),
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id, member_id)
);
CREATE INDEX consent_history ON consent_events (member_id, document_id, occurred_at DESC, id);

CREATE TABLE health_records (
  id uuid PRIMARY KEY,
  member_id uuid NOT NULL UNIQUE REFERENCES memberships(member_id),
  profile jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(profile) = 'object'),
  birth_date date,
  answers jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(answers) = 'object'),
  assessment_version varchar(80) NOT NULL,
  intake_step smallint NOT NULL DEFAULT 0 CHECK (intake_step BETWEEN 0 AND 5),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','needs_information','published')),
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  clinical_consent_event_id uuid,
  urgent boolean NOT NULL DEFAULT false,
  urgent_resolved_at timestamptz,
  information_request varchar(1000),
  submitted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id, member_id),
  FOREIGN KEY (clinical_consent_event_id, member_id) REFERENCES consent_events(id, member_id)
);
CREATE INDEX records_review_queue ON health_records (status, urgent DESC, submitted_at, id)
  WHERE status IN ('submitted','needs_information') OR urgent;

CREATE TABLE record_revisions (
  record_id uuid NOT NULL,
  version bigint NOT NULL CHECK (version >= 0),
  member_id uuid NOT NULL,
  snapshot jsonb NOT NULL CHECK (jsonb_typeof(snapshot) = 'object'),
  schema_version integer NOT NULL DEFAULT 1 CHECK (schema_version > 0),
  snapshot_sha256 char(64) NOT NULL CHECK (snapshot_sha256 ~ '^[a-f0-9]{64}$'),
  created_by uuid REFERENCES app_users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (record_id, version),
  FOREIGN KEY (record_id, member_id) REFERENCES health_records(id, member_id)
);

CREATE TABLE documents (
  id uuid PRIMARY KEY,
  record_id uuid NOT NULL,
  member_id uuid NOT NULL,
  object_key varchar(500) NOT NULL UNIQUE,
  object_version varchar(250),
  original_name varchar(120) NOT NULL,
  mime_type text NOT NULL CHECK (mime_type IN ('application/pdf','image/jpeg','image/png')),
  size_bytes bigint NOT NULL CHECK (size_bytes BETWEEN 1 AND 10485760),
  sha256 char(64) NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
  scan_status text NOT NULL DEFAULT 'pending' CHECK (scan_status IN ('pending','clean','rejected','error')),
  storage_status text NOT NULL DEFAULT 'reserved' CHECK (storage_status IN ('reserved','stored','failed','purged')),
  scan_engine_version varchar(120),
  scanned_at timestamptz,
  deleted_at timestamptz,
  purged_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (record_id, member_id) REFERENCES health_records(id, member_id),
  CHECK (scan_status <> 'clean' OR (scanned_at IS NOT NULL AND storage_status IN ('stored','purged'))),
  CHECK ((storage_status = 'purged') = (purged_at IS NOT NULL))
);
CREATE UNIQUE INDEX documents_active_checksum ON documents (member_id, sha256)
  WHERE deleted_at IS NULL AND storage_status IN ('reserved','stored');
CREATE INDEX documents_record ON documents (record_id, created_at DESC, id);
CREATE INDEX documents_scan_queue ON documents (created_at, id)
  WHERE scan_status IN ('pending','error') AND storage_status = 'stored' AND deleted_at IS NULL;

CREATE TABLE assessment_orders (
  id uuid PRIMARY KEY,
  record_id uuid NOT NULL,
  member_id uuid NOT NULL,
  product_code text NOT NULL DEFAULT 'assessment' CHECK (product_code = 'assessment'),
  pricing_version varchar(80) NOT NULL,
  amount_rial bigint NOT NULL CHECK (amount_rial BETWEEN 10000 AND 1000000000),
  status text NOT NULL CHECK (status IN ('requesting','pending','reconciliation','paid','failed','cancelled','refund_requested','partially_refunded','refunded')),
  idempotency_key varchar(120) NOT NULL,
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (record_id, member_id) REFERENCES health_records(id, member_id),
  UNIQUE (member_id, idempotency_key),
  UNIQUE (id, amount_rial),
  CHECK (status NOT IN ('paid','refund_requested','partially_refunded','refunded') OR paid_at IS NOT NULL)
);
CREATE UNIQUE INDEX orders_one_active_assessment ON assessment_orders (record_id)
  WHERE status IN ('requesting','pending','reconciliation','paid','refund_requested','partially_refunded');
CREATE INDEX orders_member ON assessment_orders (member_id, created_at DESC, id);
CREATE INDEX orders_reconciliation ON assessment_orders (updated_at, id)
  WHERE status IN ('requesting','reconciliation');

CREATE TABLE payment_attempts (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL,
  expected_amount_rial bigint NOT NULL,
  provider varchar(80) NOT NULL,
  provider_idempotency_key varchar(120) NOT NULL,
  authority varchar(150),
  provider_reference varchar(150),
  status text NOT NULL CHECK (status IN ('initiated','pending','verified','failed','unknown')),
  verified_amount_rial bigint,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (order_id, expected_amount_rial) REFERENCES assessment_orders(id, amount_rial),
  UNIQUE (provider, provider_idempotency_key),
  UNIQUE (provider, authority),
  UNIQUE (provider, provider_reference),
  CHECK (status <> 'verified' OR (authority IS NOT NULL AND provider_reference IS NOT NULL AND verified_at IS NOT NULL AND verified_amount_rial IS NOT NULL AND verified_amount_rial = expected_amount_rial))
);
CREATE UNIQUE INDEX payment_one_verified ON payment_attempts (order_id) WHERE status = 'verified';
CREATE INDEX payment_order ON payment_attempts (order_id, created_at DESC, id);

CREATE TABLE refunds (
  id uuid PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES assessment_orders(id),
  amount_rial bigint NOT NULL CHECK (amount_rial > 0),
  status text NOT NULL CHECK (status IN ('requested','processing','succeeded','failed','unknown')),
  idempotency_key varchar(120) NOT NULL,
  provider varchar(80),
  provider_reference varchar(150),
  requested_by uuid NOT NULL REFERENCES app_users(id),
  reason varchar(1000) NOT NULL,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (order_id, idempotency_key),
  UNIQUE (provider, provider_reference),
  CHECK (status <> 'succeeded' OR (completed_at IS NOT NULL AND provider IS NOT NULL AND provider_reference IS NOT NULL))
);
CREATE INDEX refunds_order ON refunds (order_id, created_at DESC, id);

CREATE TABLE care_plans (
  id uuid PRIMARY KEY,
  record_id uuid NOT NULL,
  member_id uuid NOT NULL,
  version integer NOT NULL CHECK (version > 0),
  source_record_version bigint NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewer_display_name varchar(140) NOT NULL,
  reviewer_role text NOT NULL DEFAULT 'clinician' CHECK (reviewer_role = 'clinician'),
  summary text NOT NULL CHECK (char_length(summary) BETWEEN 20 AND 4000),
  published_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (record_id, member_id) REFERENCES health_records(id, member_id),
  FOREIGN KEY (record_id, source_record_version) REFERENCES record_revisions(record_id, version),
  FOREIGN KEY (reviewer_id, reviewer_role) REFERENCES user_roles(user_id, role),
  UNIQUE (record_id, version),
  UNIQUE (record_id, source_record_version),
  UNIQUE (id, member_id)
);

CREATE TABLE plan_actions (
  id uuid PRIMARY KEY,
  plan_id uuid NOT NULL,
  member_id uuid NOT NULL,
  position smallint NOT NULL CHECK (position BETWEEN 1 AND 12),
  title varchar(160) NOT NULL CHECK (char_length(title) >= 3),
  reason varchar(500) NOT NULL CHECK (char_length(reason) >= 5),
  due_date date NOT NULL,
  owner text NOT NULL CHECK (owner IN ('member','team')),
  FOREIGN KEY (plan_id, member_id) REFERENCES care_plans(id, member_id),
  UNIQUE (plan_id, position),
  UNIQUE (id, plan_id, member_id)
);
CREATE INDEX actions_member_due ON plan_actions (member_id, due_date, id);

CREATE TABLE action_events (
  id uuid PRIMARY KEY,
  plan_id uuid NOT NULL,
  action_id uuid NOT NULL,
  member_id uuid NOT NULL,
  actor_id uuid NOT NULL REFERENCES app_users(id),
  sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
  done boolean NOT NULL,
  evidence varchar(400) NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (action_id, plan_id, member_id) REFERENCES plan_actions(id, plan_id, member_id)
);
CREATE INDEX actions_latest_state ON action_events (action_id, sequence DESC);
CREATE INDEX action_member_history ON action_events (member_id, sequence DESC);

CREATE TABLE coordination_tasks (
  id uuid PRIMARY KEY,
  member_id uuid NOT NULL REFERENCES memberships(member_id),
  kind text NOT NULL CHECK (kind IN ('booking','urgent')),
  status text NOT NULL,
  title varchar(160) NOT NULL,
  preferred varchar(300),
  provider_name varchar(160),
  scheduled_at timestamptz,
  legacy_schedule_text varchar(80),
  confirmation_reference varchar(120),
  coordination_consent_event_id uuid,
  center_consent_event_id uuid,
  assigned_to uuid REFERENCES app_users(id),
  note varchar(1000),
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id, member_id),
  FOREIGN KEY (coordination_consent_event_id, member_id) REFERENCES consent_events(id, member_id),
  FOREIGN KEY (center_consent_event_id, member_id) REFERENCES consent_events(id, member_id),
  CHECK ((kind = 'booking' AND status IN ('requested','contacted','confirmed','completed','cancelled')) OR (kind = 'urgent' AND status IN ('open','resolved'))),
  CHECK (kind <> 'booking' OR coordination_consent_event_id IS NOT NULL),
  CHECK (status NOT IN ('confirmed','completed') OR (provider_name IS NOT NULL AND scheduled_at IS NOT NULL AND confirmation_reference IS NOT NULL AND center_consent_event_id IS NOT NULL))
);
CREATE UNIQUE INDEX urgent_one_open ON coordination_tasks (member_id) WHERE kind = 'urgent' AND status = 'open';
CREATE INDEX booking_queue ON coordination_tasks (status, created_at, id) WHERE kind = 'booking';
CREATE INDEX task_member ON coordination_tasks (member_id, created_at DESC, id);
CREATE INDEX task_assignee ON coordination_tasks (assigned_to, status, created_at, id);

CREATE TABLE task_events (
  id uuid PRIMARY KEY,
  task_id uuid NOT NULL,
  member_id uuid NOT NULL,
  actor_id uuid NOT NULL REFERENCES app_users(id),
  version bigint NOT NULL CHECK (version > 0),
  from_status varchar(40) NOT NULL,
  to_status varchar(40) NOT NULL,
  note varchar(1000),
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (task_id, member_id) REFERENCES coordination_tasks(id, member_id),
  UNIQUE (task_id, version)
);

CREATE TABLE support_tickets (
  id uuid PRIMARY KEY,
  member_id uuid NOT NULL REFERENCES memberships(member_id),
  kind text NOT NULL CHECK (kind IN ('issue','suggestion','export','deletion','refund')),
  status text NOT NULL CHECK (status IN ('open','in_progress','waiting_member','resolved','rejected')),
  page varchar(80),
  assigned_to uuid REFERENCES app_users(id),
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX support_member ON support_tickets (member_id, created_at DESC, id);
CREATE INDEX support_queue ON support_tickets (status, created_at, id);

CREATE TABLE support_messages (
  id uuid PRIMARY KEY,
  ticket_id uuid NOT NULL REFERENCES support_tickets(id),
  author_id uuid NOT NULL REFERENCES app_users(id),
  body varchar(2000) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX support_thread ON support_messages (ticket_id, created_at, id);

CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  actor_type text NOT NULL CHECK (actor_type IN ('user','system','provider')),
  actor_id uuid REFERENCES app_users(id),
  subject_id uuid REFERENCES app_users(id),
  action varchar(100) NOT NULL,
  resource_type varchar(80) NOT NULL,
  resource_id varchar(120),
  outcome text NOT NULL CHECK (outcome IN ('success','denied','failure')),
  request_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((actor_type = 'user') = (actor_id IS NOT NULL))
);
CREATE INDEX audit_subject ON audit_events (subject_id, created_at DESC, id);
CREATE INDEX audit_actor ON audit_events (actor_id, created_at DESC, id);
CREATE INDEX audit_created_brin ON audit_events USING brin (created_at);

CREATE TABLE outbox_events (
  id uuid PRIMARY KEY,
  event_key varchar(200) NOT NULL UNIQUE,
  event_type varchar(120) NOT NULL,
  aggregate_type varchar(80) NOT NULL,
  aggregate_id uuid NOT NULL,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  dispatched_at timestamptz
);
CREATE INDEX outbox_pending ON outbox_events (created_at, id) WHERE dispatched_at IS NULL;

CREATE TABLE jobs (
  id uuid PRIMARY KEY,
  outbox_event_id uuid REFERENCES outbox_events(id),
  kind varchar(120) NOT NULL,
  dedupe_key varchar(200) NOT NULL UNIQUE,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  status text NOT NULL DEFAULT 'ready' CHECK (status IN ('ready','running','succeeded','dead')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts integer NOT NULL DEFAULT 8 CHECK (max_attempts > 0),
  available_at timestamptz NOT NULL DEFAULT now(),
  locked_by varchar(120),
  lease_token uuid,
  lease_expires_at timestamptz,
  last_error_code varchar(120),
  finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'running') = (locked_by IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)),
  CHECK (status = 'running' OR (locked_by IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL)),
  CHECK (status NOT IN ('succeeded','dead') OR finished_at IS NOT NULL)
);
CREATE INDEX jobs_ready ON jobs (available_at, created_at, id) WHERE status = 'ready';
CREATE INDEX jobs_expired_lease ON jobs (lease_expires_at, id) WHERE status = 'running';

CREATE TABLE idempotency_keys (
  actor_id uuid NOT NULL REFERENCES app_users(id),
  scope varchar(120) NOT NULL,
  key varchar(120) NOT NULL,
  request_sha256 char(64) NOT NULL CHECK (request_sha256 ~ '^[a-f0-9]{64}$'),
  status text NOT NULL CHECK (status IN ('started','completed')),
  response_status integer CHECK (response_status BETWEEN 100 AND 599),
  response_body jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (actor_id, scope, key),
  CHECK (expires_at > created_at),
  CHECK (status <> 'completed' OR response_status IS NOT NULL)
);
CREATE INDEX idempotency_expiration ON idempotency_keys (expires_at);

COMMENT ON TABLE record_revisions IS 'Append-only. Snapshot includes consent, assessment definition version and document hashes; see role grants in design.';
COMMENT ON TABLE care_plans IS 'Published plans only; append-only. Corrections publish a new version.';
COMMENT ON TABLE plan_actions IS 'Immutable prescribed actions. Progress is appended to action_events.';
COMMENT ON TABLE audit_events IS 'Append-only metadata, no clinical text, OTP, tokens, provider payloads or plaintext IP.';
COMMENT ON TABLE service_capacity IS 'Admission requires locking this row in every enable/disable/create path; see design. Not an automatic database trigger.';
COMMENT ON TABLE jobs IS 'At-least-once execution. External effects need provider idempotency/reconciliation and lease-token fencing.';

COMMIT;
